version: "3.9"
services:
  denji-db:
    image: postgres
    restart: no
    environment:
      POSTGRES_DB: denji
      POSTGRES_USER: denji
      POSTGRES_PASSWORD: denji
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "20002:5432"
    volumes:
      - denji-db:/var/lib/postgresql/data
  denji-migrator:
    build: .
    depends_on:
      denji-db:
        condition: service_healthy
    restart: no
    environment:
      MODE: MIGRATOR
      Database__ConnectionString: "Host=denji-db;Port=5432;Username=denji;Password=denji;Database=denji;"
  denji:
    build: .
    depends_on:
      denji-migrator:
        condition: service_completed_successfully
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/localhost.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: localhost
      ASPNETCORE_URLS: "http://+;https://+"
      Cors__Origins__0: "http://localhost:20020"
      Cosmo__BaseUrl: "http://localhost:20020"
      MODE: WEB
    ports:
      - "20000:443"
    volumes:
      - /Users/dk/.aspnet/https/localhost.pfx:/https/localhost.pfx
volumes:
  denji-db: