name: chart
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/chart.yml
      - chart/denji/**
jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    env:
      project: denji
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the chart version
        id: version
        uses: mikefarah/yq@master
        with:
          cmd: yq '.version' ./chart/${{ env.project }}/Chart.yaml
      - name: Publish
        run: |
          helm registry login -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io/${{ github.repository_owner }}/${{ env.project }}
          helm package chart/${{ env.project }} -d dist
          helm push dist/${{ env.project }}-${{ steps.version.outputs.result }}.tgz oci://ghcr.io/${{ github.repository_owner }}
